name:                diff-styles-monads
version:             0.1.0.0
github:              "nik-kor/diff-styles-monads"
license:             BSD3
# author:              "Author name here"
# maintainer:          "example@example.com"
# copyright:           "2018 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nik-kor/diff-styles-monads#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- transformers
- containers
- split
- ilist

library:
  source-dirs: src

executables:
  diff-styles-monads-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - diff-styles-monads

tests:
  diff-styles-monads-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - diff-styles-monads
    - hspec
