name:                mtl-style
version:             0.1.0.0
github:              "nik-kor/diff-styles-monads"
license:             BSD3


dependencies:
- base >= 4.7 && < 5
- mtl
- transformers
- containers
- split
- ilist
- common

library:
  source-dirs: src

executables:
  mtl-styles-monads-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -fno-warn-name-shadowing
    - -fwarn-tabs
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - mtl-style

tests:
  styles-monads-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mtl-style
    - hspec
