name:                common
version:             0.1.0.0
github:              "nik-kor/diff-styles-monads"
license:             BSD3

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src
  exposed-modules: Common

